# .github/workflows/terraform-apply.yml
name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Create Service Account key file
        run: echo '${{ secrets.YC_SA_KEY_JSON }}' > key.json

      - name: Terraform Init
        # Инициализация без бэкенда
        run: terraform init -backend=false

      - name: Terraform Plan
        run: terraform plan -var="cloud_id=${{ secrets.YC_CLOUD_ID }}" -var="folder_id=${{ secrets.YC_FOLDER_ID }}" -var="subnet_id=${{ secrets.YC_SUBNET_ID }}"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var="cloud_id=${{ secrets.YC_CLOUD_ID }}" -var="folder_id=${{ secrets.YC_FOLDER_ID }}" -var="subnet_id=${{ secrets.YC_SUBNET_ID }}"